#!/usr/bin/env python3
"""Sync canonical JSON into the Python package and generated R definitions."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data"
PYTHON_TARGET = ROOT / "src" / "pascoe_plot_style" / "data"
R_TARGET = ROOT / "R" / "pascoe_data.R"


def r_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def named_vector(values: dict[str, str], indent: str = "  ") -> str:
    lines = [f"{r_string(key)}={r_string(value)}" for key, value in values.items()]
    return "c(\n" + indent + (",\n" + indent).join(lines) + "\n)"


def plain_vector(values: list[str], indent: str = "  ") -> str:
    return "c(\n" + indent + (",\n" + indent).join(r_string(value) for value in values) + "\n)"


def flatten_presets(presets: dict) -> dict[str, dict[str, str]]:
    flattened: dict[str, dict[str, str]] = {}

    def walk(node: dict, path: list[str]) -> None:
        if node and all(isinstance(value, str) for value in node.values()):
            flattened["_".join(path)] = node
            return
        for key, value in node.items():
            if isinstance(value, dict):
                walk(value, [*path, key])

    for key, value in presets.items():
        if isinstance(value, dict):
            walk(value, [key])
    return flattened


def generate_r_data(master: dict, palettes: dict, presets: dict) -> str:
    palette_vectors: dict[str, list[str]] = {}
    for group in ("film", "qualitative", "sequential", "diverging"):
        palette_vectors.update(palettes[group])

    lines = [
        "# Generated by scripts/sync_palette_data.py; edit data/*.json instead.",
        "",
        "pascoe_master <- " + named_vector(master),
        "",
        "pascoe_palettes <- list(",
    ]
    palette_items = []
    for name, values in palette_vectors.items():
        palette_items.append(f"  {r_string(name)}={plain_vector(values, indent='    ')}")
    lines.append(",\n".join(palette_items))
    lines.extend([")", "", "pascoe_presets <- list("])
    preset_items = []
    for name, values in flatten_presets(presets).items():
        preset_items.append(f"  {r_string(name)}={named_vector(values, indent='    ')}")
    lines.append(",\n".join(preset_items))
    lines.extend([
        ")",
        "",
        "pascoe_ui <- " + named_vector(palettes["ui"]),
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    PYTHON_TARGET.mkdir(parents=True, exist_ok=True)
    for filename in ("master.json", "palettes.json", "presets.json"):
        shutil.copy2(SOURCE / filename, PYTHON_TARGET / filename)
        print(f"synced Python data: {filename}")

    master = json.loads((SOURCE / "master.json").read_text(encoding="utf-8"))
    palettes = json.loads((SOURCE / "palettes.json").read_text(encoding="utf-8"))
    presets = json.loads((SOURCE / "presets.json").read_text(encoding="utf-8"))
    R_TARGET.write_text(generate_r_data(master, palettes, presets), encoding="utf-8")
    print(f"generated R data: {R_TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
